---
title: "R Notebook"
output: html_notebook
---

Drug Review Dataset 

Read the tsv files
```{r}
library(readxl)
train <- read_xlsx(path = "C:/Users/rinavi/Desktop/Drug.xlsx", sheet = "Train", range = cell_cols("A:G"))
test <- read_xlsx(path = "C:/Users/rinavi/Desktop/Drug.xlsx", sheet = "Test", range = cell_cols("A:G"))

```

```{r}
str(train)
head(train)

```
Question 1
how many times a drug is quoted as "has side effects" or "has no side effect"
```{r}
library(tidytext)
Train = as_tibble(train)
reviews = Train %>%mutate(linenumber = row_number())%>% unnest_tokens(word, Review)
nrc_joy <- get_sentiments("nrc") %>% 
  filter(sentiment == "joy")

reviews %>%
  filter(drugName == "Valsartan") %>%
  inner_join(nrc_joy) %>%
  count(word, sort = TRUE)

library(tidyr)

 drug_sentiments<- reviews %>%
  inner_join(get_sentiments("bing")) %>%
  count(drugName, index= linenumber %/% 10, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)
 
 library(ggplot2)

ggplot(drug_sentiments, aes(index,sentiment, fill = drugName)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~drugName, ncol = 2, scales = "free_x")
```


